### PR TITLE
Season level stats

### LINKED ISSUE #93: Publish seasonal aggregates for player stats
Currently, nflverse-data hosts the `player_stats` feed containing player records on a per-game basis. If you want that data aggregated across a season, though, you need to go back to nflfastR and use `calculate_player_stats()`.

nfl_data_py provides a semi-equivalent function - `import_seasonal_data()` - that pulls and aggregates the weekly data. However, keeping the aggregation logic synced between the two functions in different languages is redundant and error-prone. If the result of `calculate_player_stats(weekly = FALSE)` were published in the feed or in its own separate feed, it'd ensure everyone is getting the same final dataset regardless of package used. It also sets nflreadR up to surface the dataset.

### PR DESCRIPTION
**Pull request by mrcaseb**
closes #93

### CODE REVIEW

**Review by tanho63 — APPROVED** [review]
eyeballing LGTM (won’t be at a computer for a while)

**Comment by mrcaseb** [comment]
I have triggered a 2023 rebuild from this branch. This will be the best test to see if everything works fine

**Comment by tanho63** [comment]
We should add use-public-rspm: true to all setup-r calls, and maybe add nflverse r-universe as well?

**Comment by alecglen** [comment]
Small nitpick: the corresponding nfl-data-py function param calls the "REG+POST" category "ALL". Thoughts on naming it to match?

Just a thought, I'm kind of ambivalent on it. I like that "REG+POST" is very concrete, whereas new users might find "ALL" ambiguous as to whether it includes pre-season.

**Comment by tanho63** [comment]
Prefer reg+post myself for the same reasons although we could just embrace the nflverse telling people that the preseason doesn’t exist

**Comment by mrcaseb** [comment]
Yeah I prefer "REG+POST" over "ALL" as it is very clear about what it is

**Pull request merged**
